//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFeBR.EmissorNFe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DFeBR.EmissorNFe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista infoComplementeres&quot;&gt;
        ///    &lt;li style=&quot;border: none; height: 15px;&quot;&gt;
        ///        &lt;label&gt;DADOS ADICIONAIS&lt;/label&gt;
        ///    &lt;/li&gt;
        ///    &lt;li id=&quot;liReservadoAoFisco&quot; style=&quot;width: 29%; min-height: 100px; height: auto;&quot;&gt;
        ///        &lt;label&gt;RESERVADO AO FISCO&lt;/label&gt;
        ///        &lt;p style=&quot;padding:4px 2px 2px 2px; word-wrap: break-word; font-size: 0.67em;&quot;&gt;#FiscoInformation#&lt;/p&gt;
        ///    &lt;/li&gt;
        ///    &lt;li id=&quot;liInfoComplementares&quot; style=&quot;width: 70%; min-height: 100px; height: auto;&quot;&gt;
        ///        &lt;label&gt;INFORMAÇÕES COMPLEME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdditionalInformation_Mod55 {
            get {
                return ResourceManager.GetString("AdditionalInformation_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width:100%; height:1px&quot;&gt;&lt;/div&gt;
        ///&lt;span style=&quot;margin-top:10px&quot;&gt;#Informations#&lt;/span&gt;.
        /// </summary>
        internal static string AdditionalInformation_Mod65 {
            get {
                return ResourceManager.GetString("AdditionalInformation_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;htmlEmitente1&quot;&gt;
        ///    #Issuer#
        ///&lt;/div&gt;
        ///&lt;div style=&quot;margin-top: 5px;&quot;&gt;
        ///    #Recipient#
        ///&lt;/div&gt;
        ///&lt;div style=&quot;margin-top: 5px;&quot;&gt;
        ///    #Invoice#
        ///&lt;/div&gt;
        ///&lt;div style=&quot;margin-top: 5px;&quot;&gt;
        ///    #Totals#
        ///&lt;/div&gt;
        ///&lt;div class=&quot;produtos&quot; style=&quot;margin-top: 5px;&quot;&gt;
        ///    #Transport#
        ///&lt;/div&gt;
        ///&lt;div id=&quot;htmlProdutos1&quot; class=&quot;produtos&quot;&gt;
        ///    &lt;ul class=&quot;lista&quot;&gt;
        ///        &lt;li style=&quot;border: none; height: 16px;&quot;&gt;
        ///            &lt;label&gt;DADOS DOS PRODUTOS/SERVIÇOS&lt;/label&gt;
        ///        &lt;/li&gt;
        ///    &lt;/ul&gt;
        ///    &lt;table id=&quot;tableProdu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body_Mod55 {
            get {
                return ResourceManager.GetString("Body_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;bordaDivisora&quot;&gt;
        ///    &lt;div class=&quot;content100 bold&quot; style=&quot;float: none; margin: auto; text-align: center; margin-top: 10px;&quot;&gt;        
        ///        DOCUMENTO AUXILIAR DA NOTA FISCAL DE CONSUMIDOR ELETRÔNICA        
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;content100&quot; style=&quot;float: none; margin: auto; text-align: center; margin-top: 10px;&quot;&gt;
        ///        NÃO PERMITE APROVEITAMENTO DE CRÉDITO DE ICMS
        ///    &lt;/div&gt;
        ///    &lt;div runat=&quot;server&quot; id=&quot;tipoEmissao&quot; class=&quot;content100 bold&quot; style=&quot;float: none; margin: auto; text-align [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Body_Mod65 {
            get {
                return ResourceManager.GetString("Body_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;margin-top:5px;float: left;width: 100%;text-align: center;&quot;&gt;&lt;b&gt;#WithOutValue#&lt;/b&gt;&lt;/span&gt;
        ///&lt;span&gt;NFC-e Número #DocumentNumber# Série #Serie# Emissão em #Emission#&lt;/span&gt;
        ///&lt;span&gt;Consulte pela Chave de Acesso em #URL#&lt;/span&gt;
        ///&lt;span&gt;CHAVE DE ACESSO&lt;/span&gt;
        ///&lt;span class=&quot;bold&quot;&gt;#NFeID#&lt;/span&gt;.
        /// </summary>
        internal static string Data_Mod65 {
            get {
                return ResourceManager.GetString("Data_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;marcaDaAgua ng-hide&quot; id=&quot;waterMark&quot; style=&quot;text-align: center;&quot;&gt;
        ///    #WaterMark#
        ///    &lt;br /&gt;
        ///    #WithOutValue#
        ///&lt;/span&gt;.
        /// </summary>
        internal static string Footer_Mod55 {
            get {
                return ResourceManager.GetString("Footer_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;bordaDivisora&quot; style=&quot;text-align: center;&quot; id=&quot;DadosQrCode&quot;&gt;
        ///    &lt;b&gt;#ContingencyMessage#&lt;/b&gt;
        ///    &lt;span&gt;Consulta via leitor de QR Code &lt;/span&gt;
        ///    &lt;img src=&quot;#QrCode#&quot; style=&quot;width:150px; height:150px; margin:auto;&quot; /&gt;
        ///    &lt;span&gt;#Protocolo#&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;span style=&quot;font-size: 0.9em; display: block; margin: auto; width: 100%; text-align: center;&quot;&gt;#Credit#&lt;/span&gt;
        /// .
        /// </summary>
        internal static string Footer_Mod65 {
            get {
                return ResourceManager.GetString("Footer_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///    &lt;ul class=&quot;lista infoTopo&quot; style=&quot;width: 79%; padding-bottom: 15px; margin-bottom:15px; border-bottom:1px dashed;&quot;&gt;
        ///        &lt;li style=&quot;width: 30%;&quot;&gt;
        ///            &lt;label&gt;DATA DE RECEBIMENTO&lt;/label&gt;
        ///        &lt;/li&gt;
        ///        &lt;li style=&quot;width: 69%; position: relative !important;&quot;&gt;
        ///            &lt;label&gt;RECEBEMOS DE #IssuerCompanyName# OS PRODUTOS/SERVIÇOS CONSTANTES DA NOTA FISCAL INDICADA AO LADO&lt;/label&gt;
        ///        &lt;/li&gt;
        ///        &lt;li style=&quot;width: 20%;&quot;&gt;
        ///            &lt;label&gt;VLR TOTAL NOTA&lt;/label&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Header_Mod55 {
            get {
                return ResourceManager.GetString("Header_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;bordaDivisora&quot; runat=&quot;server&quot; id=&quot;DadosEmitente&quot; style=&quot;border-bottom: 1px black solid&quot;&gt;
        ///   
        ///    &lt;div id=&quot;dadosemissor&quot; style=&quot;#cssDadosEmissor#&quot;&gt;
        ///        &lt;div class=&quot;content100 bold&quot; style=&quot;font-size:14px&quot;&gt;#CompanyName#&lt;/div&gt;
        ///        &lt;div class=&quot;content100&quot;&gt;CNPJ - #CNPJ#&lt;/div&gt;
        ///        &lt;div class=&quot;content100&quot;&gt;Inscrição Estadual - #IE#&lt;/div&gt;
        ///        &lt;div class=&quot;content100&quot;&gt;#Address#&lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Header_Mod65 {
            get {
                return ResourceManager.GetString("Header_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;border: none; height: 16px;&quot;&gt;
        ///        &lt;label&gt;FATURA&lt;/label&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 99.2%; font-size:0.8em; min-height: 37px; height: auto;&quot;&gt;
        ///        #InvoiceItems#      
        ///    &lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string Invoice_Mod55 {
            get {
                return ResourceManager.GetString("Invoice_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;margin: 0 5px 0 5px; font-weight:normal; width: auto; float:left;&quot;&gt;#BillItem#&lt;/p&gt;.
        /// </summary>
        internal static string InvoiceItem_Mod55 {
            get {
                return ResourceManager.GetString("InvoiceItem_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;border: none; height: 15px;&quot;&gt;
        ///        &lt;label&gt;CÁLCULO DO ISSQN&lt;/label&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 24.6%;&quot;&gt;
        ///        &lt;label&gt;VALOR DO ISSQN&lt;/label&gt;
        ///        &lt;span&gt;#ISSAmount#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 24.6%;&quot;&gt;
        ///        &lt;label&gt;BASE DE CÁLCULO DO ISSQN&lt;/label&gt;
        ///        &lt;span&gt;#ISSCalculationBasisAmount#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 24.6%;&quot;&gt;
        ///        &lt;label&gt;VALOR TOTAL DOS SERVIÇOS&lt;/label&gt;
        ///        &lt;span&gt;#ServicesAmount#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISSQN_Mod55 {
            get {
                return ResourceManager.GetString("ISSQN_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot; style=&quot;width: 100%;&quot;&gt;
        ///    &lt;li style=&quot;width: 41%; height: 160px;&quot;&gt;
        ///        &lt;img alt=&quot;&quot; style=&quot;width: 97%; margin: auto; height: 40px; margin: 5px 15px 5px 5px;&quot; src=&quot;#BarCode#&quot; /&gt;
        ///        &lt;ul class=&quot;lista&quot;&gt;
        ///            &lt;li style=&quot;width: 96%; margin: 0 5px 0 0;&quot;&gt;
        ///                &lt;label&gt;CHAVE DE ACESSO&lt;/label&gt;
        ///                &lt;span style=&quot;font-size: 0.7em; text-align: center; font-weight: bold;&quot;&gt;#VerificationCode# &lt;/span&gt;
        ///            &lt;/li&gt;
        ///            &lt;li style=&quot;border: none; width: 9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Issuer_Mod55 {
            get {
                return ResourceManager.GetString("Issuer_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;pageBreaker&quot;&gt;&lt;/div&gt;
        ///&lt;div&gt;
        ///    #Issuer#
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;produtos&quot;&gt;
        ///    &lt;ul class=&quot;lista&quot;&gt;
        ///        &lt;li style=&quot;border: none; height: 16px;&quot;&gt;
        ///            &lt;label&gt;DADOS DOS PRODUTOS/SERVIÇOS&lt;/label&gt;
        ///        &lt;/li&gt;
        ///    &lt;/ul&gt;
        ///    &lt;table id=&quot;tableProdutos2&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;display: block; width: 100%;&quot;&gt;
        ///        &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th style=&quot;border-color: black; border-top: 1px black solid; width: 6%;&quot;&gt;COD PROD&lt;/th&gt;
        ///            &lt;th style=&quot;width: 42%;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NextPage_Mod55 {
            get {
                return ResourceManager.GetString("NextPage_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;totals&quot;&gt;
        ///    &lt;th style=&quot;width: 60%;&quot;&gt;#Description#&lt;/th&gt;
        ///    &lt;th style=&quot;width: 38%; text-align:right;&quot;&gt;#Value#&lt;/th&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string Payments_Mod65 {
            get {
                return ResourceManager.GetString("Payments_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;th style=&quot;width: 5%;&quot;&gt;#ProductCode#&lt;/th&gt;
        ///    &lt;th style=&quot;text-align: left; width: 42%;&quot;&gt;#Description#&lt;/th&gt;
        ///    &lt;th style=&quot;width: 4%;&quot;&gt;#NCM#&lt;/th&gt;
        ///    &lt;th style=&quot;width: 3%;&quot;&gt;#ProductOrigin#&lt;/th&gt;
        ///    &lt;th style=&quot;width: 3%;&quot;&gt;#CFOP#&lt;/th&gt;
        ///    &lt;th style=&quot;width: 3%;&quot;&gt;#Unit#&lt;/th&gt;
        ///    &lt;th style=&quot;text-align: right; width: 5%;&quot;&gt;#Quantity#&lt;/th&gt;
        ///    &lt;th style=&quot;text-align: right; width: 5.5%;&quot;&gt;#UnityValue#&lt;/th&gt;
        ///    &lt;th style=&quot;text-align: right; width: 5.5%;&quot;&gt;#Amount#&lt;/th&gt;
        ///    &lt;th style=&quot;text-align: right [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Products_Mod55 {
            get {
                return ResourceManager.GetString("Products_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;products-nfce&quot;&gt;
        ///    &lt;td style=&quot;width: 10%&quot;&gt;#Code#&lt;/td&gt;
        ///    &lt;td style=&quot;width: 48%;&quot;&gt;#Description#&lt;/td&gt;
        ///    &lt;td style=&quot;width: 15%;&quot;&gt;#UnityValue#&lt;/td&gt;
        ///    &lt;td style=&quot;width: 10%;&quot;&gt;#Unit#&lt;/td&gt;
        ///    &lt;td style=&quot;width: 10%;&quot;&gt;#Quantity#&lt;/td&gt;
        ///    &lt;td style=&quot;width: 15%;&quot;&gt;#Amount#&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string Products_Mod65 {
            get {
                return ResourceManager.GetString("Products_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;border: none; height: 16px;&quot;&gt;
        ///        &lt;label&gt;DESTINATÁRIO/REMETENTE&lt;/label&gt;
        ///        &lt;span&gt;&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 15%;&quot;&gt;
        ///        &lt;label&gt;DATA DA EMISSÃO&lt;/label&gt;
        ///        &lt;span&gt;#EmissionDate#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 18.9%;&quot;&gt;
        ///        &lt;label&gt;CPF/CNPJ&lt;/label&gt;
        ///        &lt;span&gt;#CpfCnpj#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li id=&quot;nomeDestinatario&quot; style=&quot;width: 65%;&quot;&gt;
        ///        &lt;label&gt;NOME/RAZÃO SOCIAL&lt;/label&gt;
        ///        &lt;span style=&quot;float: left;&quot;&gt;#CompanyNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Recipient_Mod55 {
            get {
                return ResourceManager.GetString("Recipient_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;#Recipient#&lt;/span&gt;
        ///#Data#
        ///#Address#.
        /// </summary>
        internal static string Recipient_Mod65 {
            get {
                return ResourceManager.GetString("Recipient_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///    var pageHeight = #pageHeigth#;
        ///
        ///    var htmlEmitente = document.getElementById(&apos;htmlEmitente1&apos;).innerHTML;
        ///    htmlEmitente = htmlEmitente.replace(&quot;##FA##&quot;, 1);
        ///    htmlEmitente = htmlEmitente.replace(&quot;##TF##&quot;, 1);
        ///    document.getElementById(&apos;htmlEmitente1&apos;).innerHTML = htmlEmitente;
        ///
        ///    document.getElementById(&apos;waterMark&apos;).style.top = &quot;#waterMarkTop#&quot;;
        ///    document.getElementById(&apos;waterMark&apos;).style.left = &quot;#waterMarkLeft#&quot;;
        ///
        ///    var rodape = document.getElementById(&apos;textRodape&apos;);        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script_Mod55 {
            get {
                return ResourceManager.GetString("Script_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head runat=&quot;server&quot;&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: Times New Roman;
        ///            display: flow-root;
        ///            /*overflow: auto;
        ///            overflow-x: hidden;
        ///            overflow-y: hidden;*/
        ///            /*width: 21cm;
        ///            height: 29.7cm;
        ///            margin: 30mm 45mm 30mm 45mm;*/ 
        ///        }
        ///
        ///        .borda {
        ///            border: 1px black solid;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Structure_Mod55 {
            get {
                return ResourceManager.GetString("Structure_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @page {
        ///            margin: 0;
        ///        }
        ///        @media print {
        ///            body {
        ///                margin: 0;
        ///            }
        ///        }
        ///        body {
        ///            font-family: &apos;Courier&apos;;
        ///            overflow: auto;
        ///            overflow-x: hidden;
        ///            overflow-y: hidden;
        ///            margin: 0px;
        ///            padding: 0px;
        ///        }
        ///
        ///        div  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Structure_Mod65 {
            get {
                return ResourceManager.GetString("Structure_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;margin-top:5px;float: left;width: 100%;&quot;&gt;#Taxes#&lt;/span&gt;.
        /// </summary>
        internal static string Taxes_Mod65 {
            get {
                return ResourceManager.GetString("Taxes_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;border: none; height: 16px;&quot;&gt;
        ///        &lt;label&gt;CÁLCULO DO IMPOSTO&lt;/label&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 19.6%;&quot;&gt;
        ///        &lt;label&gt;VALOR TOTAL DOS PRODUTOS&lt;/label&gt;
        ///        &lt;span&gt;#ProductsAmount#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 19.7%;&quot;&gt;
        ///        &lt;label&gt;VALOR DO ICMS ST&lt;/label&gt;
        ///        &lt;span&gt;#ICMSSTAmount#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 19.7%;&quot;&gt;
        ///        &lt;label&gt;BASE DE CÁLCULO DO ICMS ST&lt;/label&gt;
        ///        &lt;span&gt;#ICMSSTCalculationBasisAmount#&lt;/span&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Total_Mod55 {
            get {
                return ResourceManager.GetString("Total_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;totals&quot;&gt;
        ///    &lt;th style=&quot;width: 60%;&quot;&gt;QTD. TOTAL DE ITENS&lt;/th&gt;
        ///    &lt;th style=&quot;width: 38%; text-align:right;&quot;&gt;#Quantity#&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;tr class=&quot;totals&quot;&gt;
        ///    &lt;th style=&quot;width: 60%;&quot;&gt;VALOR TOTAL&lt;/th&gt;
        ///    &lt;th style=&quot;width: 38%; text-align:right;&quot;&gt;#TotalValue#&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;tr class=&quot;totals&quot;&gt;
        ///    &lt;th style=&quot;width: 60%;&quot;&gt;VALOR DESCONTO&lt;/th&gt;
        ///    &lt;th style=&quot;width: 38%; text-align:right;&quot;&gt;#TotalDiscount#&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;tr class=&quot;totals&quot;&gt;
        ///    &lt;th style=&quot;width: 60%;&quot;&gt;&lt;b&gt;VALOR A PAGAR&lt;/b&gt;&lt;/th&gt;
        ///    &lt;th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Total_Mod65 {
            get {
                return ResourceManager.GetString("Total_Mod65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;lista&quot;&gt;
        ///    &lt;label&gt;REBOQUES DO VEÍCULO&lt;/label&gt;
        ///&lt;/div&gt;
        ///&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width: 99.8%;margin-left: 2px&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;th style=&quot;width: 40%;&quot;&gt;PLACA&lt;/th&gt;
        ///        &lt;th style=&quot;width: 40%;&quot;&gt;RNTC&lt;/th&gt;
        ///        &lt;th style=&quot;width: 20%;&quot;&gt;UF&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///  
        ///    #TrailerItems#
        ///&lt;/table&gt;.
        /// </summary>
        internal static string Trailer_Mod55 {
            get {
                return ResourceManager.GetString("Trailer_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;th&gt;#Plate#&lt;/th&gt;
        ///    &lt;th&gt;#RNTC#&lt;/th&gt;
        ///    &lt;th&gt;#StateCode#&lt;/th&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string TrailerItem_Mod55 {
            get {
                return ResourceManager.GetString("TrailerItem_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;border: none; height:16px;&quot;&gt;
        ///        &lt;label&gt;TRANSPORTADOR/VOLUMES TRANSPORTADOS&lt;/label&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 13%; font-size:0.8em;&quot;&gt;
        ///        &lt;label&gt;CNPJ/CPF&lt;/label&gt;
        ///        &lt;span&gt;#CpfCnpj#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 4%;&quot;&gt;
        ///        &lt;label&gt;UF&lt;/label&gt;
        ///        &lt;span&gt;#VehicleState#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 11%; font-size:0.8em;&quot;&gt;
        ///        &lt;label&gt;PLACA DO VEÍCULO&lt;/label&gt;
        ///        &lt;span&gt;#VehiclePlate#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transport_Mod55 {
            get {
                return ResourceManager.GetString("Transport_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;width: 19%;&quot;&gt;
        ///        &lt;label&gt;PESO LÍQUIDO&lt;/label&gt;
        ///        &lt;span&gt;#NetWeight#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 20%;&quot;&gt;
        ///        &lt;label&gt;PESO BRUTO&lt;/label&gt;
        ///        &lt;span&gt;#GrossWeight#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 20%;&quot;&gt;
        ///        &lt;label&gt;MARCA&lt;/label&gt;
        ///        &lt;span&gt;#Brand#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 20%;&quot;&gt;
        ///        &lt;label&gt;ESPÉCIE&lt;/label&gt;
        ///        &lt;span&gt;#Specie#&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 19.2%;&quot;&gt;
        ///        &lt;label&gt;QUANTIDADE&lt;/labe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Volume_Mod55 {
            get {
                return ResourceManager.GetString("Volume_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;lista&quot;&gt;
        ///    &lt;li style=&quot;width: 19%;&quot;&gt;
        ///        &lt;label&gt;PESO LÍQUIDO&lt;/label&gt;
        ///        &lt;span&gt;&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 20%;&quot;&gt;
        ///        &lt;label&gt;PESO BRUTO&lt;/label&gt;
        ///        &lt;span&gt;&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 20%;&quot;&gt;
        ///        &lt;label&gt;MARCA&lt;/label&gt;
        ///        &lt;span&gt;&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 20%;&quot;&gt;
        ///        &lt;label&gt;ESPÉCIE&lt;/label&gt;
        ///        &lt;span&gt;&lt;/span&gt;
        ///    &lt;/li&gt;
        ///    &lt;li style=&quot;width: 19.2%;&quot;&gt;
        ///        &lt;label&gt;QUANTIDADE&lt;/label&gt;
        ///        &lt;span&gt;&lt;/span&gt;
        ///    &lt;/li&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Volumes_Mod55 {
            get {
                return ResourceManager.GetString("Volumes_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display: block; width: 100%; height: 16px;&quot;&gt;
        ///    &lt;label&gt;VOLUMES TRANSPORTADOS&lt;/label&gt;
        ///&lt;/div&gt;
        ///&lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;width:100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;th style=&quot;width: 15%;&quot;&gt;QUANTIDADE&lt;/th&gt;
        ///        &lt;th style=&quot;width: 20%;&quot;&gt;ESPÉCIE&lt;/th&gt;
        ///        &lt;th style=&quot;width: 35%;&quot;&gt;MARCA&lt;/th&gt;
        ///        &lt;th style=&quot;width: 15%;&quot;&gt;PESO BRUTO&lt;/th&gt;
        ///        &lt;th style=&quot;width: 15%;&quot;&gt;PESO LÍQUIDO&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    #VolumesItems#
        ///&lt;/table&gt;.
        /// </summary>
        internal static string VolumesList_Mod55 {
            get {
                return ResourceManager.GetString("VolumesList_Mod55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;th&gt;#Quantity#&lt;/th&gt;
        ///    &lt;th&gt;#Specie#&lt;/th&gt;
        ///    &lt;th&gt;#Brand#&lt;/th&gt;
        ///    &lt;th&gt;#GrossWeight#&lt;/th&gt;
        ///    &lt;th&gt;#NetWeight#&lt;/th&gt;    
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string VolumesListItem_Mod55 {
            get {
                return ResourceManager.GetString("VolumesListItem_Mod55", resourceCulture);
            }
        }
    }
}
